# Generated by Django 3.2.5 on 2021-07-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCommServer', '0005_auto_20160908_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycommdevice',
            name='createdDate',
            field=models.DateTimeField(verbose_name='2021-07-22 11:12:22'),
        ),
        migrations.AlterField(
            model_name='mycommmsg',
            name='receivedTime',
            field=models.DateTimeField(verbose_name='2021-07-22 11:12:22'),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='receivedTime',
            field=models.DateTimeField(verbose_name='2021-07-22 11:12:22'),
        ),
    ]
